name:                unionfind
version:             0.1.0.0
github:              "davidspies/unionfind"
license:             BSD3
author:              "David Spies"
maintainer:          "dnspies@gmail.com"
copyright:           "2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/davidspies/unionfind#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- dlist

default-extensions:
- DeriveFunctor
- LambdaCase
- NamedFieldPuns
- ScopedTypeVariables
- TupleSections
- ViewPatterns

library:
  source-dirs: src
  exposed-modules:
  - UnionFind
  - UnionFind.Introspect
  ghc-options:
  - -Wall
  - -Werror

tests:
  unionfind-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - unionfind
    - hspec
    - mtl
    - QuickCheck
